services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-grocery-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
